import React from 'react'

function Price() {
    return ( 
        <div className='container border-bottom' style={{paddingBottom:"100px", paddingTop:"100px"}}>
            <div className='row text-center'>
                <h1 style={{color:"#434343"}} className='pb-3'>Pricing</h1> 
                <p style={{fontSize:"22px", color:"#424242"}} className='pb-2'>Free equity investments and flat ₹20 intraday and F&O trades</p>
            </div>
        </div>
     );
}

export default Price;